<?php
define('SQUARE_SANDBOX', true);
define('SQUARE_ACCESS_TOKEN', $_ENV['SQUARE_ACCESS'] );
define('SQUARE_APPLICATION_ID', $_ENV['SQUARE_APPLICATION']);
define('SQUARE_LOCATION_ID',$_ENV['SQUARE_LOCATION'] ); 
define('SQUARE_CURRENCY', 'USD');
define('SQUARE_VERSION_API', '2023-05-17'); 